//
//  BlocklistSignatureVerifier.swift
//  SpamSniper
//
//  Created by Codex on 3/22/26.
//

import CryptoKit
import Foundation

/// Minimal detached-signature verifier for the SpamSniper blocklist repo.
///
/// This verifier is intentionally narrow. It only supports the exact OpenPGP
/// shapes that our signing pipeline currently emits:
/// - v4 detached signature packets (`sigclass 0x00`)
/// - public-key algorithm `22`, which is OpenPGP EdDSA / Ed25519
/// - hash algorithm `10`, which is SHA-512
/// - legacy packet headers (old-format CTBs), which is what the current local
///   GnuPG export/sign flow produces
///
/// The detached-signature verification flow is:
/// 1. load the bundled trusted public key resource,
/// 2. parse the OpenPGP key packets and detached signature packet,
/// 3. identify the signing subkey using the issuer fingerprint / key ID,
/// 4. rebuild the OpenPGP v4 hashed trailer,
/// 5. hash `signedData + signedBytes + trailer` with SHA-512,
/// 6. verify the resulting digest with CryptoKit Ed25519 verification.
///
/// OpenPGP EdDSA signatures generated by the current GnuPG flow sign the
/// SHA-512 digest bytes, not the original document bytes directly. That is why
/// this verifier checks the stored hash prefix first and then verifies the
/// detached signature over the computed digest.
enum BlocklistSignatureVerifierError: LocalizedError {
    case invalidArmor
    case invalidPacket
    case unsupportedPacketFormat
    case unsupportedPublicKeyAlgorithm
    case unsupportedHashAlgorithm
    case missingSigningKey
    case malformedMPI
    case invalidPublicKey
    case invalidSignature
    case trustedKeyMissing

    var errorDescription: String? {
        switch self {
        case .invalidArmor, .invalidPacket, .unsupportedPacketFormat, .unsupportedPublicKeyAlgorithm,
             .unsupportedHashAlgorithm, .missingSigningKey, .malformedMPI, .invalidPublicKey, .invalidSignature,
             .trustedKeyMissing:
            return "The blocklist signature could not be verified."
        }
    }
}

enum BlocklistSignatureVerifier {
    static func verifyDetachedSignature(signedData: Data, signatureData: Data) throws {
        let keyring = try parseKeyring(armoredData: try trustedPublicKeyData())
        let signature = try parseDetachedSignature(armoredData: signatureData)
        guard let key = keyring.first(where: { signature.matches($0) }) else {
            throw BlocklistSignatureVerifierError.missingSigningKey
        }

        let digest = signature.hash(signedData: signedData)
        guard digest.prefix(2) == signature.hashPrefix else {
            throw BlocklistSignatureVerifierError.invalidSignature
        }

        // CryptoKit's Ed25519 verifier expects the raw 32-byte public key and
        // 64-byte signature (`r || s`). The OpenPGP parser below extracts both.
        let publicKey = try Curve25519.Signing.PublicKey(rawRepresentation: key.rawPublicKey)
        guard publicKey.isValidSignature(signature.rawSignature, for: digest) else {
            throw BlocklistSignatureVerifierError.invalidSignature
        }
    }

    private static func trustedPublicKeyData() throws -> Data {
        let bundles = [Bundle.main] + Bundle.allBundles + Bundle.allFrameworks
        for bundle in bundles {
            if let url = bundle.url(forResource: "spam-blocklist-trusted-public-key", withExtension: "asc") {
                return try Data(contentsOf: url)
            }
        }

        throw BlocklistSignatureVerifierError.trustedKeyMissing
    }

    private static func parseKeyring(armoredData: Data) throws -> [OpenPGPPublicKey] {
        let decoded = try decodeArmor(armoredData)
        var offset = 0
        var keys: [OpenPGPPublicKey] = []

        while offset < decoded.count {
            let packet = try readPacket(from: decoded, offset: &offset)
            if packet.tag == 6 || packet.tag == 14 {
                keys.append(try parsePublicKey(packetBody: packet.body))
            }
        }

        guard !keys.isEmpty else {
            throw BlocklistSignatureVerifierError.invalidPublicKey
        }

        return keys
    }

    private static func parsePublicKey(packetBody: Data) throws -> OpenPGPPublicKey {
        var offset = 0
        guard packetBody.count >= 8 else {
            throw BlocklistSignatureVerifierError.invalidPacket
        }

        let version = packetBody[offset]
        offset += 1
        guard version == 4 else {
            throw BlocklistSignatureVerifierError.invalidPacket
        }

        offset += 4 // created

        let algorithm = packetBody[offset]
        offset += 1
        // OpenPGP public-key algorithm 22 == EdDSA. Our signer emits Ed25519.
        guard algorithm == 22 else {
            throw BlocklistSignatureVerifierError.unsupportedPublicKeyAlgorithm
        }

        let oidLength = Int(packetBody[offset])
        offset += 1
        guard packetBody.count >= offset + oidLength else {
            throw BlocklistSignatureVerifierError.invalidPacket
        }
        offset += oidLength

        let mpi = try readMPI(from: packetBody, offset: &offset)
        // GnuPG encodes Ed25519 public keys as an MPI containing 0x40 + 32 bytes
        // of compressed Edwards point data. CryptoKit only wants the raw 32 bytes.
        guard let pointPrefix = mpi.first, pointPrefix == 0x40, mpi.count == 33 else {
            throw BlocklistSignatureVerifierError.invalidPublicKey
        }

        let fingerprint = Self.fingerprint(for: packetBody)
        let keyID = String(fingerprint.suffix(16))

        return OpenPGPPublicKey(
            fingerprint: fingerprint,
            keyID: keyID,
            rawPublicKey: Data(mpi.dropFirst())
        )
    }

    private static func parseDetachedSignature(armoredData: Data) throws -> OpenPGPSignature {
        let decoded = try decodeArmor(armoredData)
        var offset = 0
        let packet = try readPacket(from: decoded, offset: &offset)
        guard packet.tag == 2 else {
            throw BlocklistSignatureVerifierError.invalidPacket
        }

        let body = packet.body
        guard body.count >= 10 else {
            throw BlocklistSignatureVerifierError.invalidPacket
        }

        var cursor = 0
        try validateDetachedSignatureHeader(in: body, cursor: &cursor)

        let hashedSubpacketLength = Int(body[cursor]) << 8 | Int(body[cursor + 1])
        cursor += 2
        guard body.count >= cursor + hashedSubpacketLength else {
            throw BlocklistSignatureVerifierError.invalidPacket
        }

        let hashedSubpackets = body[cursor..<cursor + hashedSubpacketLength]
        let signatureBodyPrefix = body.prefix(cursor + hashedSubpacketLength)
        cursor += hashedSubpacketLength

        let unhashedSubpacketLength = Int(body[cursor]) << 8 | Int(body[cursor + 1])
        cursor += 2
        guard body.count >= cursor + unhashedSubpacketLength + 2 else {
            throw BlocklistSignatureVerifierError.invalidPacket
        }

        let unhashedSubpackets = body[cursor..<cursor + unhashedSubpacketLength]
        cursor += unhashedSubpacketLength

        let hashPrefix = Data(body[cursor..<cursor + 2])
        cursor += 2

        let signatureR = try readMPI(from: body, offset: &cursor)
        let signatureS = try readMPI(from: body, offset: &cursor)
        let rawSignature = signatureR + signatureS

        let issuerFingerprint = try subpackets(in: hashedSubpackets).first(where: { $0.type == 33 })?.issuerFingerprint
        let issuerKeyID = try subpackets(in: unhashedSubpackets).first(where: { $0.type == 16 })?.issuerKeyID

        return OpenPGPSignature(
            issuerFingerprint: issuerFingerprint,
            issuerKeyID: issuerKeyID,
            rawSignature: rawSignature,
            hashPrefix: hashPrefix,
            signedBytes: Data(signatureBodyPrefix),
            trailer: signatureTrailer(for: signatureBodyPrefix)
        )
    }

    private static func validateDetachedSignatureHeader(in body: Data, cursor: inout Int) throws {
        let version = body[cursor]
        cursor += 1
        guard version == 4 else {
            throw BlocklistSignatureVerifierError.invalidPacket
        }

        let signatureType = body[cursor]
        cursor += 1
        // Detached binary document signature.
        guard signatureType == 0x00 else {
            throw BlocklistSignatureVerifierError.invalidPacket
        }

        try validateSignatureAlgorithms(in: body, cursor: &cursor)
    }

    private static func validateSignatureAlgorithms(in body: Data, cursor: inout Int) throws {
        let publicKeyAlgorithm = body[cursor]
        cursor += 1
        // OpenPGP public-key algorithm 22 == EdDSA / Ed25519.
        guard publicKeyAlgorithm == 22 else {
            throw BlocklistSignatureVerifierError.unsupportedPublicKeyAlgorithm
        }

        let hashAlgorithm = body[cursor]
        cursor += 1
        // OpenPGP hash algorithm 10 == SHA-512.
        guard hashAlgorithm == 10 else {
            throw BlocklistSignatureVerifierError.unsupportedHashAlgorithm
        }
    }

    private static func signatureTrailer<Bytes: DataProtocol>(for signatureBodyPrefix: Bytes) -> Data {
        // RFC 4880 v4 signature trailer: version, 0xff, and the 32-bit big-endian
        // length of the signature body prefix through the hashed subpackets.
        let trailerLength = UInt32(signatureBodyPrefix.count)
        return Data([0x04, 0xff]) + withUnsafeBytes(of: trailerLength.bigEndian, Array.init)
    }

    private static func decodeArmor(_ armoredData: Data) throws -> Data {
        guard let text = String(data: armoredData, encoding: .utf8) else {
            throw BlocklistSignatureVerifierError.invalidArmor
        }

        let base64Body = text
            .split(whereSeparator: \.isNewline)
            .map(String.init)
            .filter { line in
                !line.hasPrefix("-----") &&
                !line.hasPrefix("Version:") &&
                !line.hasPrefix("Comment:") &&
                !line.hasPrefix("=")
            }
            .joined()

        guard let data = Data(base64Encoded: base64Body) else {
            throw BlocklistSignatureVerifierError.invalidArmor
        }

        return data
    }

    private static func readPacket(from data: Data, offset: inout Int) throws -> (tag: Int, body: Data) {
        guard offset < data.count else {
            throw BlocklistSignatureVerifierError.invalidPacket
        }

        let ctb = data[offset]
        guard (ctb & 0x80) != 0 else {
            throw BlocklistSignatureVerifierError.invalidPacket
        }

        let usesNewFormat = (ctb & 0x40) != 0
        // This parser currently supports only legacy packet headers because that
        // is what our local signing/export flow emits today.
        guard !usesNewFormat else {
            throw BlocklistSignatureVerifierError.unsupportedPacketFormat
        }

        let tag = Int((ctb >> 2) & 0x0f)
        let lengthType = ctb & 0x03
        let headerLength: Int
        let packetLength: Int

        switch lengthType {
        case 0:
            headerLength = 2
            packetLength = Int(data[offset + 1])
        case 1:
            headerLength = 3
            packetLength = Int(data[offset + 1]) << 8 | Int(data[offset + 2])
        case 2:
            headerLength = 5
            packetLength = Int(data[offset + 1]) << 24 |
                Int(data[offset + 2]) << 16 |
                Int(data[offset + 3]) << 8 |
                Int(data[offset + 4])
        default:
            throw BlocklistSignatureVerifierError.unsupportedPacketFormat
        }

        let bodyStart = offset + headerLength
        let bodyEnd = bodyStart + packetLength
        guard bodyEnd <= data.count else {
            throw BlocklistSignatureVerifierError.invalidPacket
        }

        offset = bodyEnd
        return (tag, data[bodyStart..<bodyEnd])
    }

    private static func readMPI(from data: Data, offset: inout Int) throws -> Data {
        guard data.count >= offset + 2 else {
            throw BlocklistSignatureVerifierError.malformedMPI
        }

        let bitLength = Int(data[offset]) << 8 | Int(data[offset + 1])
        offset += 2
        let byteLength = (bitLength + 7) / 8
        guard data.count >= offset + byteLength else {
            throw BlocklistSignatureVerifierError.malformedMPI
        }

        let mpi = data[offset..<offset + byteLength]
        offset += byteLength
        return Data(mpi)
    }

    private static func subpackets(in data: Data.SubSequence) throws -> [OpenPGPSignatureSubpacket] {
        var offset = data.startIndex
        var packets: [OpenPGPSignatureSubpacket] = []

        while offset < data.endIndex {
            let (length, nextOffset) = try readSubpacketLength(in: data, offset: offset)
            guard length > 0 else {
                throw BlocklistSignatureVerifierError.invalidPacket
            }

            let typeOctetIndex = nextOffset
            let bodyStart = data.index(after: typeOctetIndex)
            let bodyEnd = data.index(bodyStart, offsetBy: length - 1)
            guard bodyEnd <= data.endIndex else {
                throw BlocklistSignatureVerifierError.invalidPacket
            }

            let type = data[typeOctetIndex] & 0x7f
            let packetBody = Data(data[bodyStart..<bodyEnd])
            packets.append(OpenPGPSignatureSubpacket(type: type, body: packetBody))
            offset = bodyEnd
        }

        return packets
    }

    private static func readSubpacketLength(
        in data: Data.SubSequence,
        offset: Data.SubSequence.Index
    ) throws -> (Int, Data.SubSequence.Index) {
        let first = Int(data[offset])
        if first < 192 {
            return (first, data.index(after: offset))
        }

        if first < 255 {
            let secondIndex = data.index(after: offset)
            let second = Int(data[secondIndex])
            let length = ((first - 192) << 8) + second + 192
            return (length, data.index(after: secondIndex))
        }

        let start = data.index(after: offset)
        let end = data.index(start, offsetBy: 4)
        guard end <= data.endIndex else {
            throw BlocklistSignatureVerifierError.invalidPacket
        }

        let length = Int(data[start]) << 24 |
            Int(data[data.index(start, offsetBy: 1)]) << 16 |
            Int(data[data.index(start, offsetBy: 2)]) << 8 |
            Int(data[data.index(start, offsetBy: 3)])
        return (length, end)
    }

    private static func fingerprint(for packetBody: Data) -> String {
        let length = UInt16(packetBody.count).bigEndian
        let prefix = Data([0x99]) + withUnsafeBytes(of: length, Array.init)
        let digest = Insecure.SHA1.hash(data: prefix + packetBody)
        return digest.map { String(format: "%02X", $0) }.joined()
    }
}

private struct OpenPGPPublicKey {
    let fingerprint: String
    let keyID: String
    let rawPublicKey: Data
}

private struct OpenPGPSignature {
    let issuerFingerprint: String?
    let issuerKeyID: String?
    let rawSignature: Data
    let hashPrefix: Data
    let signedBytes: Data
    let trailer: Data

    func matches(_ key: OpenPGPPublicKey) -> Bool {
        if let issuerFingerprint {
            return issuerFingerprint.caseInsensitiveCompare(key.fingerprint) == .orderedSame
        }

        if let issuerKeyID {
            return issuerKeyID.caseInsensitiveCompare(key.keyID) == .orderedSame
        }

        return false
    }

    func hash(signedData: Data) -> Data {
        // OpenPGP EdDSA verification in our signing setup is performed over the
        // SHA-512 digest of the document plus the v4 signature trailer payload.
        Data(SHA512.hash(data: signedData + signedBytes + trailer))
    }
}

private struct OpenPGPSignatureSubpacket {
    let type: UInt8
    let body: Data

    var issuerFingerprint: String? {
        guard type == 33, body.count == 21, body.first == 4 else {
            return nil
        }

        return body.dropFirst().map { String(format: "%02X", $0) }.joined()
    }

    var issuerKeyID: String? {
        guard type == 16, body.count == 8 else {
            return nil
        }

        return body.map { String(format: "%02X", $0) }.joined()
    }
}
